# Generated by Django 4.2.7 on 2023-11-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=3000, null=True),
                ),
                (
                    "side_effects",
                    models.TextField(blank=True, max_length=3000, null=True),
                ),
                (
                    "dosage_form",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("strength", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "sell_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("pack_size", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        null=True,
                        upload_to="images/",
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                ("total_quantity", models.IntegerField(default=0)),
                (
                    "alternate_brand",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("categories", models.CharField(blank=True, max_length=250, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "manufacturer_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("manufacturer_address", models.TextField(blank=True, null=True)),
                ("composition", models.TextField(blank=True, null=True)),
                ("prescription_required", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("rating", models.FloatField(blank=True, null=True)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
    ]
