# Generated by Django 4.2.7 on 2023-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0004_category_remove_medicine_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="image",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to=""
            ),
        ),
    ]
