# Generated by Django 4.2.7 on 2023-11-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0007_remove_medicine_dosage_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="alternate_brand",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="manufacturer_address",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="manufacturer_name",
        ),
        migrations.CreateModel(
            name="MedicineAlternateBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicines.manufacturer",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicines.medicine",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="medicine",
            name="alternate_brands",
            field=models.ManyToManyField(
                blank=True,
                related_name="alternate_brands",
                through="medicines.MedicineAlternateBrand",
                to="medicines.manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medicines.manufacturer",
            ),
        ),
    ]
