# Generated by Django 4.2.7 on 2023-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0008_manufacturer_remove_medicine_alternate_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
