# Generated by Django 4.2.7 on 2023-11-30 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0009_medicine_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="alternate_brands",
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="manufacturer_images/"
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="patient_package_insert",
            field=models.FileField(
                blank=True, null=True, upload_to="medicine_pdf_files/"
            ),
        ),
        migrations.AddField(
            model_name="medicinetype",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="medicine_type_images/"
            ),
        ),
        migrations.DeleteModel(
            name="MedicineAlternateBrand",
        ),
    ]
