# Generated by Django 4.2.7 on 2023-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0010_remove_medicine_alternate_brands_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicine",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="medicine",
            name="unit_of_measurement",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
