# Generated by Django 4.2.7 on 2023-12-11 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0011_alter_medicine_options_medicine_unit_of_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="medicine_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medicines.medicinetype",
            ),
        ),
    ]
