# Generated by Django 4.2.7 on 2023-12-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0012_alter_medicine_medicine_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
