# Generated by Django 4.2.7 on 2023-12-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0014_alter_manufacturer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="prescription_required",
            field=models.BooleanField(default=True),
        ),
    ]
