# Generated by Django 4.2.8 on 2024-01-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0016_medicine_returnable_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='refrigerated',
            field=models.BooleanField(default=False),
        ),
    ]
