# Generated by Django 4.2.8 on 2024-01-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0017_medicine_refrigerated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='refrigerated',
        ),
    ]
